src/TechChallenge.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using TechChallenge.Application;
using TechChallenge.Application.UseCases.CreateProduct;
using TechChallenge.Application.Queries;
using TechChallenge.Web.Models;

namespace TechChallenge.Web.Controllers;

[ApiController]
[Route("api/v1/products")]
public class ProductController : ControllerBase
{
    private readonly IProductQueries _productQueries;
    private readonly ICreateProductUseCase _createProductUseCase;

    public ProductController(IProductQueries productQueries, ICreateProductUseCase createProductUseCase)
    {
        _productQueries = productQueries;
        _createProductUseCase = createProductUseCase;
    }

    [HttpGet]
    public async Task<IActionResult> GetAllAsync(CancellationToken cancellationToken)
    {
        var product = await _productQueries.GetAllAsync(cancellationToken);

        return product is not null ? Ok(product) : NoContent();
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetByIdAsync([FromRoute(Name = "id")] Guid productId, CancellationToken cancellationToken)
    {
        var product = await _productQueries.GetByIdAsync(productId, cancellationToken);

        return product is not null ? Ok(product) : NoContent();
    }

    [HttpPost]
    public async Task<IActionResult> CreateProductAsync(CreateProductViewModel viewModel, CancellationToken cancellationToken)
    { 
        CreateProductUseCaseInput input = new()
        {
            Name = viewModel.Name,
            Description = viewModel.Description,
            Price = viewModel.Price
        };

        var product = await _createProductUseCase.ExecuteAsync(input, cancellationToken);

        return Ok(product);
    }
}

src/TechChallenge.Web/Pages/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using TechChallenge.Application;
using TechChallenge.Application.UseCases.CreateImage;
using TechChallenge.Application.UseCases.CreateProduct;

namespace TechChallenge.Web.Pages.Products
{
    [BindProperties]
    public class CreateModel : PageModel
    {
        private readonly ICreateProductUseCase _createProductUseCase;
        private readonly ICreateImageUseCase _createImageUseCase;

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public decimal Price { get; set; }

        public CreateModel(
            ICreateProductUseCase createProductUseCase,
            ICreateImageUseCase createImageUseCase)
        {
            _createProductUseCase = createProductUseCase;
            _createImageUseCase = createImageUseCase;
        }

        public async Task<IActionResult> OnPost(List<IFormFile> files)
        {
            CreateProductUseCaseInput productInput = new()
            {
                Name = Name,
                Description = Description,
                Price = Price
            };

            var product = await _createProductUseCase.ExecuteAsync(productInput);

            if (product != null)
            {
                foreach (var file in files)
                {
                    using var stream = file.OpenReadStream();
                    CreateImageUseCaseInput imageInput = new()
                    {
                        Stream = stream,
                        Extension = "",
                        ProductId = product.Id
                    };
                    var image = await _createImageUseCase.ExecuteAsync(imageInput);
                }
            }

            return RedirectToPage("Index");
        }
    }
}

src/TechChallenge.Web/Pages/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TechChallenge.Application.Queries;
using TechChallenge.Application.UseCases.ClearImages;
using TechChallenge.Application.UseCases.DeleteProduct;
using TechChallenge.Domain.Entities;

namespace TechChallenge.Web.Pages.Products
{
    [BindProperties]
    public class DeleteModel : PageModel
    {
        private readonly IProductQueries _productQueries;
        private readonly IDeleteProductUseCase _deleteProductUseCase;
        private readonly IClearImagesUseCase _clearImagesUseCase;
        private readonly ILogger<IndexModel> _logger;

        public Product Product { get; set; }

        public DeleteModel(
            ILogger<IndexModel> logger,
            IProductQueries productQueries,
            IDeleteProductUseCase deleteProductUseCase,
            IClearImagesUseCase clearImagesUseCase)
        {
            _logger = logger;
            _productQueries = productQueries;
            _deleteProductUseCase = deleteProductUseCase;
            _clearImagesUseCase = clearImagesUseCase;
        }

        public async Task OnGet(Guid? id)
        {
            Product = await _productQueries.GetByIdAsync((Guid)id);
        }

        public async Task<IActionResult> OnPost()
        {
            await _clearImagesUseCase.ExecuteAsync(Product.Id);
            await _deleteProductUseCase.ExecuteAsync(Product.Id);
            return RedirectToPage("Index");
        }
    }
}

src/TechChallenge.Web/Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TechChallenge.Application;
using TechChallenge.Application.Queries;
using TechChallenge.Application.UseCases.CreateImage;
using TechChallenge.Application.UseCases.DeleteImage;
using TechChallenge.Application.UseCases.EditProduct;
using TechChallenge.Domain.Entities;

namespace TechChallenge.Web.Pages.Products
{
    [BindProperties]
    public class EditModel : PageModel
    {
        private readonly IProductQueries _productQueries;
        private readonly ICreateImageUseCase _createImageUseCase;
        private readonly IDeleteImageUseCase _deleteImageUseCase;
        private readonly IEditProductUseCase _editProductUseCase;
        private readonly ILogger<IndexModel> _logger;

        public Product Product { get; set; }

        public EditModel(
            ILogger<IndexModel> logger,
            IProductQueries productQueries,
            IDeleteImageUseCase deleteImageUseCase,
            ICreateImageUseCase createImageUseCase,
            IEditProductUseCase editProductUseCase)
        {
            _logger = logger;
            _productQueries = productQueries;
            _deleteImageUseCase = deleteImageUseCase;
            _createImageUseCase = createImageUseCase;
            _editProductUseCase = editProductUseCase;
        }

        public async Task OnGet(Guid? id)
        {
            Product = await _productQueries.GetByIdAsync((Guid)id);
        }

        public async Task<IActionResult> OnPost(List<IFormFile> files)
        {
            await _editProductUseCase.ExecuteAsync(Product);

            foreach (var file in files)
            {
                using var stream = file.OpenReadStream();
                CreateImageUseCaseInput imageInput = new()
                {
                    Stream = stream,
                    Extension = "",
                    ProductId = Product.Id
                };
                await _createImageUseCase.ExecuteAsync(imageInput);
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostRemove(Guid imageId)
        {
            await _deleteImageUseCase.ExecuteAsync(imageId);
            return RedirectToPage(new { id = Product.Id });
        }
    }
}

src/TechChallenge.Web/Pages/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using TechChallenge.Application.Queries;
using TechChallenge.Domain.Entities;

namespace TechChallenge.Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly IProductQueries _productQueries;
        private readonly ILogger<IndexModel> _logger;

        public List<Product> Products { get; private set; }

        public IndexModel(
            IProductQueries productQueries,
            ILogger<IndexModel> logger)
        {
            _productQueries = productQueries;
            _logger = logger;
        }

        public async Task OnGet()
        {
            Products = await _productQueries.GetAllAsync();
        }


    }
}

src/TechChallenge.Web/Pages/Products/Create.cshtml
@page
@model TechChallenge.Web.Pages.Products.CreateModel

<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Criar Produto
            </h2>
            <hr/>
        </div>
        <div asp-validation-summary="All">
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
            <div class="mb-3">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
            <div class="mb-3">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>
            <div class="mb-3">
                <label>Imagens</label>
                <input type="file" name="files" multiple="multiple" class="form-control" />
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">
            Criar Produto
        </button>
    </div>
</form>

src/TechChallenge.Web/Pages/Products/Delete.cshtml
@page
@model TechChallenge.Web.Pages.Products.DeleteModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Atualizar Produto</h2>
            <hr />
        </div>
        <div>
            <div class="mb-3">
                <label asp-for="Product.Id"></label>
                <input asp-for="Product.Id" class="form-control" readonly="readonly" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Name"></label>
                <input asp-for="Product.Name" class="form-control" readonly="readonly" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Description"></label>
                <input asp-for="Product.Description" class="form-control" readonly="readonly" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Price"></label>
                <input asp-for="Product.Price" class="form-control" readonly="readonly" />
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">
            Excluir
        </button>
    </div>
</form>

src/TechChallenge.Web/Pages/Products/Edit.cshtml
@page
@model TechChallenge.Web.Pages.Products.EditModel

<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Atualizar Produto</h2>
            <hr />
        </div>
        <div asp-validation-summary="All">
            <div class="mb-3">
                <label asp-for="Product.Id"></label>
                <input asp-for="Product.Id" class="form-control" readonly="readonly" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Name"></label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Description"></label>
                <input asp-for="Product.Description" class="form-control" />
                <span asp-validation-for="Product.Description" class="text-danger" />
            </div>
            <div class="mb-3">
                <label asp-for="Product.Price"></label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger" />
            </div>
            <div class="mb-3">
                <label>Images</label>
                <ul style="list-style: none">
                    @foreach (var image in Model.Product.Images)
                    {
                        <li style="display: inline-block">
                            <div>
                                <img src="@image.Url" style="width:100px">
                                <br />
                                <button type="submit" class="btn btn-outline-danger"
                                asp-page-handler="remove" asp-route-imageId="@image.Id">
                                Excluir
                            </button>
                            </div>
                        </li>
                    }
                </ul>
                <input type="file" name="files" multiple="multiple" class="form-control" />
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">
            Atualizar
        </button>
    </div>
</form>

src/TechChallenge.Web/Pages/Products/Index.cshtml
@page
@model TechChallenge.Web.Pages.Products.IndexModel

<div class="container">
    <div class="mail-box">
        <aside class="lg-side">
            <div class="inbox-head">
                <h3>Produtos</h3>
            </div>
            <a class="btn btn-primary btn-sx pull-left" style="margin-top:20px;margin-bottom: 20px;"
               asp-page="/Products/Create">
                Novo produto
            </a>
            <div class="inbox-body" style="margin-top:20px;">
                <div class="mail-option">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr class="unread">
                                <th class="col-sm-2 view-message  dont-show" style="width: min-content">Id</th>
                                <th class="view-message col-sm-2">Nome</th>
                                <th class="view-message col-sm-3">Descrição</th>
                                <th class="view-message col-sm-2">Preço</th>
                                <th>Imagem</th>
                                <th class="col-sm-1">Comando</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Products)
                            {
                                <tr>
                                    <td class="view-message  dont-show">
                                        <h5>@item.Id</h5>
                                    </td>
                                    <td class="view-message">
                                        <h5>@item.Name</h5>
                                    </td>
                                    <td class="view-message">
                                        <h5>@item.Description</h5>
                                    </td>
                                    <td class="view-message text-left">
                                        <h5>@string.Format("{0:C}", @item.Price)</h5>
                                    </td>
                                    <td>
                                        <table>
                                            <tbody>
                                                @foreach (var image in item.Images)
                                                {
                                                    <tr>
                                                        <td>
                                                            <img src="@image.Url" style="width:100px">
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </td>
                                    <td>
                                        <form method="post">
                                            <span class="btn-group pull-right">
                                                <a class="btn btn-warning btn-xs" asp-page="Edit"
                                                   asp-route-id="@item.Id" style="height: min-content">
                                                    Editar
                                                </a>
                                                <a class="btn btn-danger btn-xs" asp-page="Delete"
                                                   asp-route-id="@item.Id" style="height: min-content">
                                                    Excluir
                                                </a>
                                            </span>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </aside>
    </div>
</div>